### ISSUE TITLE
Last release broke BC

### ISSUE THREAD

**Issue by sunkan** [ellipsephp/dispatcher#1]
Hi

Commit 7b8e567d4340483f4c88765782c137319ee40fc3 broke backwards compatible

Is't it possible to revert release and do a major version bump?

**Comment by pmall** [comment]
Hi @sunkan 

I know I released multiple BC breaks, I plan on adding another one today.

- `Ellipse\Dispatcher\FallbackResponse` is now `Ellipse\Handlers\FallbackRequestHandler`
- I plan to also move `Ellipse\Dispatcher\ComposableResolver` to its own package

Are you able to update your code or do you really need a major version? I released this package too soon it would be v16 something by following semver. It should really stay stable after those two updates I promise.

Sorry for the inconvenience.

**Comment by pmall** [comment]
I released [1.6.0](https://github.com/ellipsephp/dispatcher/releases/tag/1.6.0) with a notice about breaking changes since 1.4.0.

Please let me know if you need more assistance to get this working.

**Comment by sunkan** [comment]
I solved it by fixing the version to 1.4.0 in the project where it became a problem.

When I get time I'll refactor the project that I depend on to use the new FallbackRequestHandler
